config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'application/profile'
  get 'application/admin_profile'
  get 'application/employee_profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'
  resources :addresses
  resources :orders
  resources :services

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  #Relationships
  has_many :addresses
  has_many :orders
  has_many :services
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_many :services
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client

  validates :order_status, presence: true
  validates :order_total_value, presence: true
  validates :client_id, presence: true

  def checkout(order_id)
      @order = current_user.client.orders.where(order_id: order_id)
      @order.update(order_status:  "Procesando")
  end
  
  #Relationships
  has_many :services
  
end
 

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :order
  belongs_to :employee, optional: true
  belongs_to :client
  belongs_to :address

  paginates_per 5

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # Relationships between roles
  has_one :admin
  has_one :client, dependent: :destroy
  has_one :employee

  after_create :create_client

  validates :first_name, presence: true, length: { maximum:50 }
  validates :last_name, presence: true, length: { maximum:50 }
  validates :dni, presence: true
  validates :phone, presence: true

  def create_client  
    if employee.blank? && admin.blank?
      client ||= Client.create(user_id: id)
    end
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!

  def index 
    @addresses = current_user.client.addresses
  end

  def new
    @address = current_user.client.addresses.new
  end

  def create 
    @address = current_user.client.addresses.create(address_params)
    if @address.save
      flash[:success] = 'La dirección fue creada exitosamente.'
      redirect_to addresses_path
    else
      flash.now[:danger] = 'Información invalida'
      render 'new'
    end
  end

  def edit 
    @address = current_user.client.addresses.find(params[:id])
  end

  def update 
    @address = current_user.client.addresses.find(params[:id])
    if @address.update(address_params)
      flash[:success] = 'Dirección actualizada.'
      redirect_to addresses_path 
    else
      flash.now[:danger] = 'Información Invalida.'
      render 'edit'
    end
  end

  private

  def address_params
    params.require(:address).permit(:address_description, :address, :address_complement, :phone)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permited_parameters, if: :devise_controller?
  def home
  end
  private

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :dni, :phone, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone, :address])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @order = current_user.client.order.new
  end

  def show
  end

  def index
    @orders = current_user.client.orders.all
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order

  # TODO: Faltan acciones y revisar que funcione
  def index
    @services = if current_user.admin
                  Service.all.page params[:page]
                elsif current_user.employee
                  current_user.employee.services.where(employee_id: current_user.employee.id).page params[:page]
                else
                  current_user.client.services.page params[:page]
                end
  end

  def new
    @service = @order.services.new
  end

  def create
    @service = @order.services.create(service_params.merge(client_id: current_user.client.id))
    if @service.save
      flash[:success] = 'El servicio se agrego al carrito.'
      redirect_to orders_path
    else
      flash.now[:danger] = "Información Invalida: #{@service.errors.full_messages.join(', ')} "
      render 'new'
    end
  end

  def show
    @service = if current_user.admin
                 Service.all.find(params[:id])
               else
                 current_user.client.services.find(params[:id])
               end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      flash[:success] = 'Registro actualizado'
      redirect_to services_path
    else
      render 'edit'
    end
  end

  private

  def service_params
    params.require(:service).permit(:service_description, :employee_id, :service_status, :service_date, :address_id)
  end

  def set_order
    if current_user.client
      @order = current_user.client.orders.where(order_status: 'Creada').first
      @order || @order = current_user.client.orders.create
    end
  end

  def order_params
    params.require(:order).permit(:order_status, :order_total_value)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: @address) do |f|%>
  <div class="field">
    <%= f.label :address_description, 'Descripción de la Dirección', class: 'label' %>
    <%= f.text_area :address_description, class: 'input', required: true, placeholder: 'Descripción...' %>
  </div>
  <div class="field">
    <%= f.label :address, 'Dirección', class: 'label' %>
    <%= f.text_field :address, class: 'input', required: true, placeholder: 'Dirección' %>
  </div>
  <div class="field">
    <%= f.label :address_complement, 'Apto, Torre, etc', class: 'label' %>
    <%= f.text_field :address_complement, class: 'input', placeholder: 'Complemento' %>
  </div>
  <div class="field">
    <%= f.label :phone,'Teléfono', class: 'label' %>
    <%= f.number_field :phone, class: 'input', required: true %>
  </div>
  <div class="actions">
    <%= f.submit  id:"formbutton", class: 'button is-primary' %>
  </div>
  <%= link_to "Atras", :back %>
<% end %>

app/views/addresses/edit.html.erb
<div class="container">
  <div class="box">
      <div class="form">
          <h1 class="tittle">Editar Dirección</h1></br>
          <%= render 'form'%></div>
      </div>
  </div>
</div>

app/views/addresses/index.html.erb
<div class="container">
  <div class="box">
    <div class="container">
      <h1 class="tittle">Tus direcciones</h1></br>
      <div class="container">
        <table class="table is-striped">
          <thead>
            <tr>
              <th>Descripción</th>
              <th>Dirección</th>
              <th>Complemento</th>
              <th>Teléfono</th>
            </tr>
          </thead>
          <tbody>
            <% @addresses.each do |address|%>
              <tr>
                <td><%= address.address_description%></td>
                <td><%= address.address%></td>
                <td><%= address.address_complement%></td>
                <td><%= address.phone%></td>
                <td>
                  <%= link_to edit_address_path(address.id), class: 'button is-success is-small' do %>
                    <i class="fas fa-indent">Editar</i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      
      <%= link_to 'Nueva Dirección', new_address_path, id:"newdirectionbutton", class:"button is-primary" %>
      <%= link_to "Atras", :back %>
    </div>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="container">
    <div class="box">
        <div class="form">
            <h1 class="tittle">Nueva Dirección</h1></br>
            <%= render 'form'%></div>
        </div>
    </div>
</div>

app/views/application/admin_profile.html.erb
<% if current_user.admin.present? %>
    <div class="container">
        <div class="box">
            <div class="profile">
                <article class="panel is-info">
                    <p class="panel-heading">
                        Mi Perfil
                    </p>
                    <%= link_to 'Servicios', services_path, class:"panel-block is-active" %>
                </article>

                <div class="tile is-parent">
                    <article id="profile" class="tile is-child notification is-info ">
                        <div class="content">
                            <div class="tittle">
                                Administrador
                            </div></br>
                            <div class="subtitle">
                                <%= current_user.first_name %>, <%= current_user.last_name %>
                            </div>
                            <div class="content">
                                <%= current_user.email %>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div> 

<% else %>
    <div>
    no disponible
    </div>
<% end %>

app/views/application/cart.html.erb
<div class="container">
    <div class="box">
        <h1 class="tittle">Carrito</h1></br>



    </div>
</div>

app/views/application/employee_profile.html.erb
<% if current_user.employee.present? %>
    <div class="container">
        <div class="box">
            <div class="profile">
                <article class="panel is-warning">
                    <p class="panel-heading">
                        Mi Perfil
                    </p>
                    <%= link_to 'Servicios asignados', services_path, class:"panel-block is-active" %>
                </article>

                <div class="tile is-parent">
                    <article id="profile" class="tile is-child notification is-warning ">
                        <div class="content">
                            <div class="tittle">
                                Empleado
                            </div></br>
                            <div class="subtitle">
                                <%= current_user.first_name %>, <%= current_user.last_name %>
                            </div>
                            <div class="content">
                                <%= current_user.email %>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div> 

<% else %>
    <div>
    no disponible
    </div>
<% end %>

app/views/application/home.html.erb
<div class="tittle">
    <% unless current_user.blank? %>
        <div class="tittle">
        ¡Bienvenido! <%= current_user.first_name %>, <%= current_user.last_name %>
        </div></br>
    <% end %>
    <img class="carousel-item" src="https://media.discordapp.net/attachments/816001549146914886/816025223962689626/home-3429674_1920_1.jpg?width=1440&height=618">
</div>

app/views/application/new_service.html.erb
<div class="container">
  <div class="box">
      <div class="form">
          <h1 class="tittle">Solicitar un servicio</h1></br>
      
            <div class="field">
                <label class="label">Fecha de servicio</label>   
                <input class="input" type="email" placeholder="ejemplo@email.com">
            </div>

            <div class="field">
                <label class="label">xxxxx</label>   
                <input class="input" type="email" placeholder="xxxxx">
            </div>
          
            <div class="field">
                <label class="label">Direccion</label>   
                <input class="input" type="email" placeholder="ejemplo@email.com">
            </div>
        </div>
    </div>
  </div>

app/views/application/profile.html.erb
<div class="container">
    <div class="box">
        <div class="profile">
            <article class="panel is-primary">
                <p class="panel-heading">
                    Mi Perfil
                </p>
                <%= link_to 'Mis Servicios', services_path, class:"panel-block is-active" %>
                <%= link_to 'Mis direcciones', addresses_path, class:"panel-block is-active" %>
                <%= link_to 'Editar información', edit_user_registration_path, class:"panel-block is-active" %>
            </article>

            <div class="tile is-parent">
                <article id="profile" class="tile is-child notification is-primary ">
                    <div class="content">
                        <div class="tittle">
                            <%= current_user.first_name %>, <%= current_user.last_name %>
                        </div></br>
                        <div class="subtitle">
                            <%= current_user.phone %>
                        </div>
                        <div class="content">
                            <%= current_user.email %>
                        </div>
                    </div>
                </article>
            </div>


        </div>

    </div>
</div> 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container footer">
    <div class="footer-top">
      <img class="footlogo" src="https://media.discordapp.net/attachments/816001549146914886/816001670500712478/Hogare-Logo.png">
      <h1 class="foottittle">Hogaré</h1>
    </div>

    <div class="footer-content"></div>
    
    <div></div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="navbar-brand"  id="buttons" >
    <a class="navbar-item" href="/"  id="buttons">
      <img class="navlogo" src="https://media.discordapp.net/attachments/816001549146914886/816001670500712478/Hogare-Logo.png">
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%=link_to "Inicio", root_path, class:"navbar-item" %>

      <% unless current_user.blank? %>
      <% if current_user.admin.present? %>
        <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" id="drop">
                About
              </a>
              <a class="navbar-item" id="drop">
                Jobs
              </a>
              <a class="navbar-item" id="drop">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item" id="drop">
                Report an issue
              </a>
            </div>
          </div>
        <% else %>
        <%= link_to 'Contratar Servicio', new_service_path, class:"navbar-item" %>
        <% end %>
        
      <% end %>
    </div>

    <% unless current_user.blank? %>
      <div class="navbar-end" >
      
      <div class="navbar-item" id="buttons">
        <div class="buttons">  
          <% if current_user.admin.present? %>
            <%= link_to 'Admin', application_admin_profile_path, class:"button is-info" %>
          <% elsif current_user.employee.present?%>
            <%= link_to 'Employee', application_employee_profile_path, class:"button is-warning" %>
          <% else %>
            <a class="navbar-item" href="/orders/#{@orders.last}" id="buttons">
              <img class="cartbutton" src=" https://media.discordapp.net/attachments/816001549146914886/817175316400570388/Carrito_2.png?width=473&height=473">
            </a>
            <%= link_to 'Mi Perfil', application_profile_path, class:"button is-light" %>
          <% end %>
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:"button is-primary" %>
        </div>
      </div>
    </div>

    <% else %>
      <div class="navbar-end">
        <div class="navbar-item" id="buttons">
          <div class="buttons">
            <%= link_to 'Registrate', new_user_registration_path, class:"button is-primary"  %>
            <%= link_to 'Inicia Sesión', new_user_session_path, class:"button is-light" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hogare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%=render'layouts/header'%>
    <% flash.each do |message_type, message| %>
      <div class="notification message is-<%= message_type %>" style="margin-bottom: 0px;">
        <%=message%>
      </div>
    <% end %>
    <%= yield %>
    <%=render'layouts/footer'%>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="container">
    <div class="box">
        <div class="form">
            <h1 class="tittle">Orden</h1></br>
            <%= form_with(model: @orders) do |form| %>

                <div class="field">
                    <%= form.label "Status", class: 'label' %>
                    <%= form.select :order_status, [['Aprovado', 'Aprovado'], ['Sin Aprovar', 'Sin Aprovar']], class:"select is-rounded", selected:'Status' %>
                </div>

                <div class="field">
                    <%= form.label "Valor", class:"label"%>
                    <%= form.text_area :order_total_value, class:"input", required: true, placeholder: "Valor..." %>
                </div>
                
                <div class="field">
                    <%= form.label "ID Cliente", class:"label"%>
                    <%= form.text_area :client_id, class:"input", required: true, placeholder: "ID Cliente..." %>
                </div>

                <div class="actions">
                    <div class="control">
                        <%= form.submit "Hacer orden", class:"button is-link" %>
                    </div>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <div class="box">
    <div class="container">
      <h1 class="tittle">Tus ordenes</h1></br>
      <div class="container">
        <table class="table is-striped">
          <thead>
            <tr>
              <th>Status</th>
              <th>Valor Total</th>
              <th>Fecha de Creacción</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order|%>
              <tr>
                <td><%= order.order_status%></td>
                <td><%= order.order_total_value%></td>
                <td><%= order.created_at.strftime("%F")%></td>
                <td>
                  <%= link_to services_path(order.id), class: 'button is-success is-small' do %>
                    <i class="fas fa-indent">Ver Servicios en esta orden</i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to "Atras", :back %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form'%>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/services/_form.html.erb
<%= form_with(model: @service) do |f|%>

  <% if current_user.client.present? %>
    <div class="field">
      <%= f.label :service_description, 'Descripción del Servicio', class: 'label' %>
      <%= f.text_area :service_description, class: 'input', required: true, placeholder: 'Descripción...' %>
    </div>
    
    <div class="field">
      <%= f.label :service_date, 'Fecha Del Servicio', class: 'label' %>
      <%= f.date_field :service_date, class: 'input', required: true%>
    </div>

    <div class="field">
      <div class="minimessage">
        <em >Si no tienes una Dirección registrada haz click  </em>
        <%= link_to 'Aqui', new_address_path, class:"navbar-item" %>
      </div>
      <%= f.label :address_id,'Dirección', class: 'label' %>
      <%= f.collection_select(:address_id, current_user.client.addresses.all, :id, :address_description, :prompt => 'Seleccionar...') %>
    </div>
  <% end %>

  <% if current_user.admin.present? %>
    <div class="field">
      <%= f.label :employee_id,'Asignar Empleado', class: 'label' %>
      <%= f.collection_select(:employee_id, Employee.all, :id, :id, :prompt => 'Seleccionar...') %>
    </div>

    <div class="field">
        <%= f.label 'Asignar Estado', class: 'label' %>
        <%= f.select :service_status, [['Asignado', 'Asignado'], ['Aprovado', 'Aprovado']], class:"select is-rounded", selected:'Creado' %>
      </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit  id:"formbutton", class: 'button is-primary' %>
  </div>
<% end %>

app/views/services/edit.html.erb
<% if current_user.admin.present? %>
    <div class="container">
    <div class="box">
        <div class="form">
            <h1 class="tittle">Asignar empleados</h1></br>
            <%= render 'form'%></div>
        </div>
    </div>
    </div>
<% end %>

app/views/services/index.html.erb
<div class="container">
  <div class="box">
    <div class="container">
      <% if current_user.admin.present? %>
        <h1 class="tittle">Servicios</h1></br>
      <% else %>
        <h1 class="tittle">Tus Servicios</h1></br>
      <% end %>
      <div class="container">
        <table class="table is-striped">
          <thead>
            <tr>
                <th>Descripción</th>
                <th>Dirección</th>
                <th>Fecha</th>
                <th>Estado</th>
                <% if current_user.admin.present? %>
                    <th>Cliente</th>
                    <th> ID del Cliente</th>
                <% end %> 
                <th>Fecha de servicio</th>
            </tr>
          </thead>
          <tbody>
            <% @services.each do |s|%>
              <tr>
                <td><%= s.service_description%></td>
                <td><%= s.address.address_description%></td>
                <td><%= s.service_date%></td>
                <td><%= s.service_status%></td>
                <% if current_user.admin.present? %>
                    <td><%= s.client.user.first_name%></td>
                    <td><%= s.client.id%></td>
                <% end %>  
                <td><%= s.service_date.strftime("%F")%></td>
                <td>
                  <%=link_to "Detalles", service_path(s.id) %>
                </td>
                <% if current_user.admin.present? %>
                    <td>
                      <%=link_to "Asignar", edit_service_path(s.id) %>
                    </td>
                <% end %>  
     
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    </div>
    <%= paginate @services %>

app/views/services/new.html.erb
<div class="container">
    <div class="box">
        <div class="form">
            <h1 class="tittle">Nuevo Servicio</h1></br>
            <%= render 'form'%></div>
        </div>
    </div>
</div

app/views/services/show.html.erb
<div class="container">

    <div class="card">
        <div class="card-content">
            <div class="media">
            <div class="media-left">
                <figure class="image is-48x48">
                <img src="https://media.discordapp.net/attachments/816001549146914886/816001670500712478/Hogare-Logo.png" style="background: #c1edf9; border-radius: 50%;" alt="Placeholder image">
                </figure>
            </div>
            <div class="media-content">
                <p class="title is-4">Servicio</p>
                <p class="subtitle is-6"><%= @service.service_description %></p>
            </div>
            </div>

            <table class="table is-striped">
            <thead>
                <tr>
                    <th>Dirección</th>
                    <th></th>
                    <th>Fecha</th>
                    <th>Empleado</th>
                    <th>Estado</th>
                    <th>Fecha de servicio</th>
                    <th>Fecha de creacion</th>
                    <th>#ID</th>
                </tr>
            </thead>
            <tbody> 
                <tr>
                    <td><%= @service.address.address%></td>
                    <td><%= @service.address.address_complement%></td>
                    <td><%= @service.service_date%></td>
                    <td><%= @service.employee_id%></td>
                    <td><%= @service.service_status%></td>
                    <td><%= @service.service_date.strftime("%F")%></td>
                    <td><%= @service.created_at.strftime("%F")%></td>
                    <td><%= @service.id%></td>
                    <% if current_user.admin.present? %>
                        <td>
                        <%=link_to "Asignar", edit_service_path(@service.id) %>
                        </td>
                    <% end %> 
                </tr>
            </tbody>
        </table>
        </div>
    </div>

    <%= link_to "Atras", :back %>

</div> 